"""
Django settings for healthportal project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

import os
from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!^v-ll2--*!i)%hr@#z(#%&$ah_yr5q4k3e=&&rj(c!vqm*c3b'

# ==============================================================================
# INTEGRACIÓN CON AZURE KEY VAULT (SEMANA 6)
# ==============================================================================
KEY_VAULT_NAME = os.environ.get("KEY_VAULT_NAME")

if KEY_VAULT_NAME:
    KV_URI = f"https://{KEY_VAULT_NAME}.vault.azure.net"
    credential = DefaultAzureCredential()
    client = SecretClient(vault_url=KV_URI, credential=credential)

    try:
        PHI_MASTER_KEY = client.get_secret("PHI-MASTER-KEY").value
    except Exception as e:
        print(f"Alerta Key Vault: {e}")
        PHI_MASTER_KEY = os.environ.get("PHI_MASTER_KEY")
else:
    PHI_MASTER_KEY = os.environ.get("PHI_MASTER_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Mis aplicaciones - UQ HealthShield
    'accounts',
    'patients',
    'records',
    'consent',

    # Seguridad
    'axes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Middleware de seguridad para rate limiting
    'axes.middleware.AxesMiddleware',
    
    # Middleware de Content Security Policy (Punto 5)
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'healthportal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'healthportal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración del modelo de usuario personalizado
AUTH_USER_MODEL = 'accounts.CustomUser'

# ==========================================
# CONFIGURACIÓN DE SEGURIDAD (DJANGO-AXES)
# ==========================================
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',  # El guardián revisa primero
    'django.contrib.auth.backends.ModelBackend', # Luego pasa al login normal
]

AXES_FAILURE_LIMIT = 5  # Bloqueo después de 5 intentos fallidos (Requisito S2)
AXES_COOLOFF_TIME = 1   # Tiempo de bloqueo en horas
AXES_RESET_ON_SUCCESS = True  # Reiniciar el contador si entra bien


# ==========================================
# CONFIGURACIÓN CSP ESTRICTA (Requisito S2)
# ==========================================
CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")  # Permite estilos básicos
CSP_SCRIPT_SRC = ("'self'",)
CSP_IMG_SRC = ("'self'", "data:")              # Vital para mostrar el código QR (Base64)

# ==============================================================================
# CONFIGURACIÓN DE SEGURIDAD PARA PRODUCCIÓN (SEMANA 6 - AZURE)
# ==============================================================================

# 1. Forzar redirección a HTTPS (Obligatorio en producción)
SECURE_SSL_REDIRECT = True

# 2. Configuración estricta de HSTS (HTTP Strict Transport Security)
SECURE_HSTS_SECONDS = 31536000  # 1 año de memoria para el navegador
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# 3. Hosts permitidos (Dominio oficial + entornos locales de prueba)
ALLOWED_HOSTS = ['health.uqaisolutions.com.pe', 'localhost', '127.0.0.1']

# 4. Orígenes confiables para CSRF (Evita bloqueos en formularios a través de HTTPS)
CSRF_TRUSTED_ORIGINS = ['https://health.uqaisolutions.com.pe']