# Generated by Django 6.0.7 on 2026-07-17 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0001_initial'),
        ('patients', '0002_remove_patient_apellidos_remove_patient_dni_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='consentrecord',
            old_name='granted_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='consentrecord',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='action',
            field=models.CharField(choices=[('GRANT', 'Otorgar Acceso'), ('REVOKE', 'Revocar Acceso')], default='GRANT', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='integrity_hash',
            field=models.CharField(blank=True, default='', help_text='Firma criptográfica SHA-256', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.CreateModel(
            name='MedicalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_accesses', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_accesses', to='patients.patient')),
            ],
        ),
    ]
