# Generated by Django 5.0.7 on 2026-06-22 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='diagnostico',
            new_name='diagnostico_cifrado',
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='medicamentos',
            new_name='medicamentos_cifrados',
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='notas',
            new_name='notas_cifradas',
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records_doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
