# Generated by Django 5.0.7 on 2026-06-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='telefono',
        ),
        migrations.AddField(
            model_name='patient',
            name='apellido',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='dni_cifrado',
            field=models.TextField(default='Desconocido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='Desconocido', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='fecha_nacimiento_cifrada',
            field=models.TextField(default='Desconocido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='telefono_cifrado',
            field=models.TextField(default='Desconocido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
