name: Django CI/CD Pipeline

on:
  push:
    branches: [main, dev, "release/**"]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Ejecutar Migraciones
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Correr Pruebas con Cobertura
        run: |
          coverage run --source='.' manage.py test
          coverage report -m
